// Generated by CoffeeScript 1.12.4
(function() {
  var BaseButtonTask, ButtonTask,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BaseButtonTask = require('zooniverse-decision-tree/lib/button-task');

  ButtonTask = (function(superClass) {
    extend(ButtonTask, superClass);

    function ButtonTask() {
      return ButtonTask.__super__.constructor.apply(this, arguments);
    }

    ButtonTask.prototype.choiceTemplate = require('../templates/choice');

    return ButtonTask;

  })(BaseButtonTask);

  module.exports = ButtonTask;

}).call(this);
