// Generated by CoffeeScript 1.7.1
(function() {
  var BaseCheckboxTask, CheckboxTask,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BaseCheckboxTask = require('zooniverse-decision-tree/lib/checkbox-task');

  CheckboxTask = (function(_super) {
    __extends(CheckboxTask, _super);

    function CheckboxTask() {
      return CheckboxTask.__super__.constructor.apply(this, arguments);
    }

    CheckboxTask.prototype.choiceTemplate = require('../templates/choice');

    return CheckboxTask;

  })(BaseCheckboxTask);

  module.exports = CheckboxTask;

}).call(this);
