// Generated by CoffeeScript 1.9.0
(function() {
  var DrawingTask, RadioTask,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __hasProp = {}.hasOwnProperty;

  RadioTask = require('./radio');

  DrawingTask = (function(_super) {
    __extends(DrawingTask, _super);

    function DrawingTask() {
      return DrawingTask.__super__.constructor.apply(this, arguments);
    }

    DrawingTask.type = 'drawing';

    DrawingTask.prototype.tools = {
      point: require('../drawing-tools/point'),
      ellipse: require('marking-surface/lib/tools/ellipse'),
      rect: require('marking-surface/lib/tools/rectangle'),
      text: require('marking-surface/lib/tools/transcription')
    };

    DrawingTask.prototype.SELECT_TOOL = 'decision-tree:select-drawing-tool';

    DrawingTask.prototype.enter = function() {
      var choice, _i, _len, _ref, _results;
      DrawingTask.__super__.enter.apply(this, arguments);
      this.el.addEventListener('change', this, false);
      if (this.choices.length === 1) {
        this.reset(this.choices[0].value);
        return this.selectTool(this.choices[0].type, this.choices[0]);
      } else {
        _ref = this.choices;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          choice = _ref[_i];
          if (choice.checked) {
            this.reset(choice.value);
            _results.push(this.selectTool(choice.type, choice));
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      }
    };

    DrawingTask.prototype.exit = function() {
      DrawingTask.__super__.exit.apply(this, arguments);
      this.el.removeEventListener('change', this, false);
      return this.dispatchEvent(this.CHANGE_TOOL, null);
    };

    DrawingTask.prototype.handleEvent = function(e) {
      var choice;
      if (e.type === 'change' && e.target.hasAttribute('data-choice-index')) {
        choice = this.getChoice();
        return this.selectTool(choice.type, choice);
      } else {
        return DrawingTask.__super__.handleEvent.apply(this, arguments);
      }
    };

    DrawingTask.prototype.selectTool = function(tool, choice) {
      if (typeof tool === 'string') {
        tool = this.tools[tool];
      }
      return this.dispatchEvent(this.SELECT_TOOL, {
        tool: tool,
        choice: choice
      });
    };

    return DrawingTask;

  })(RadioTask);

  module.exports = DrawingTask;

}).call(this);
