// Generated by CoffeeScript 1.7.1
(function() {
  var BaseRadioTask, RadioTask,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BaseRadioTask = require('zooniverse-decision-tree/lib/radio-task');

  RadioTask = (function(_super) {
    __extends(RadioTask, _super);

    function RadioTask() {
      return RadioTask.__super__.constructor.apply(this, arguments);
    }

    RadioTask.prototype.choiceTemplate = require('../templates/choice');

    return RadioTask;

  })(BaseRadioTask);

  module.exports = RadioTask;

}).call(this);
