// Generated by CoffeeScript 1.9.3
(function() {
  var BaseRadioTask, RadioTask,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BaseRadioTask = require('zooniverse-decision-tree/lib/radio-task');

  RadioTask = (function(superClass) {
    extend(RadioTask, superClass);

    function RadioTask() {
      return RadioTask.__super__.constructor.apply(this, arguments);
    }

    RadioTask.prototype.choiceTemplate = require('../templates/choice');

    return RadioTask;

  })(BaseRadioTask);

  module.exports = RadioTask;

}).call(this);
