// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = {
    home: 'Нome',
    classify: 'Classify',
    profile: 'Profile',
    science: 'Výzkum',
    team: 'Team',
    getStarted: 'Get started!',
    thankYou: 'Thank you. Your classification has been recorded.',
    yes: 'Ano',
    no: 'No',
    talkQuestion: 'Do you want to talk about this image?',
    existingComments: 'There are already <span class="readymade-existing-comments-count">&mdash;</span> comments.',
    share: 'Share this image:',
    next: 'Next',
    previous: 'Previous',
    finished: 'Skončit',
    back: 'Back',
    favorite: 'Favorite',
    favoriteIcon: '<i class="fa fa-heart-o readymade-clickable-not-checked"></i>',
    favoriteIconChecked: '<i class="fa fa-heart readymade-clickable-checked" style="color: orangered;"></i>',
    hideOldMarks: 'Hide old marks',
    hideOldMarksIcon: '<i class="fa fa-eye-slash readymade-clickable-not-checked"></i>',
    hideOldMarksIconChecked: '<i class="fa fa-eye-slash readymade-clickable-checked" style="color: orangered;"></i>',
    restartTutorial: 'Restart tutorial',
    tutorialIcon: '<i class="fa fa-graduation-cap"></i>'
  };

}).call(this);
