// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = {
    home: 'Нome',
    classify: 'Klasifikace',
    profile: 'Profil',
    science: 'Výzkum',
    team: 'Tým',
    getStarted: 'Spustit klasifikaci!',
    thankYou: 'Děkujeme. Tvoje klasifikace byla uložena.',
    yes: 'Ano',
    no: 'Ne',
    talkQuestion: 'Chceš komentovat tento snímek?',
    existingComments: 'Počet komentářů k tomuto snímku: <span class="readymade-existing-comments-count">&mdash;</span>.',
    share: 'Sdílet tento snímek:',
    next: 'Další',
    previous: 'Předcházející',
    finished: 'Skončit',
    back: 'Zpět',
    favorite: 'Oblíbené',
    favoriteIcon: '<i class="fa fa-heart-o readymade-clickable-not-checked"></i>',
    favoriteIconChecked: '<i class="fa fa-heart readymade-clickable-checked" style="color: orangered;"></i>',
    hideOldMarks: 'Skrýt umístěné značky',
    hideOldMarksIcon: '<i class="fa fa-eye-slash readymade-clickable-not-checked"></i>',
    hideOldMarksIconChecked: '<i class="fa fa-eye-slash readymade-clickable-checked" style="color: orangered;"></i>',
    restartTutorial: 'Spustit tutorial',
    tutorialIcon: '<i class="fa fa-graduation-cap"></i>'
  };

}).call(this);
