// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = {
    home: 'Home',
    classify: 'Classify',
    profile: 'Profile',
    science: 'Science',
    team: 'Team',
    getStarted: 'Get started!',
    favorite: 'Favorite',
    hideOldMarks: 'Hide old marks',
    restartTutorial: 'Restart tutorial'
  };

}).call(this);
