// Generated by CoffeeScript 1.9.1
(function() {
  module.exports = {
    home: 'Inicio',
    classify: 'Clasificar',
    profile: 'Perfil',
    science: 'Ciencia',
    team: 'Equipo',
    getStarted: 'Comienza aquí!',
    thankYou: 'Gracias. Su clasificación se ha registrado.',
    yes: 'Sí',
    no: 'No',
    talkQuestion: '¿Quiere comentar sobre esta imagen?',
    existingComments: 'Ya hay <span class="readymade-existing-comments-count">&mdash;</span> comentario(s).',
    share: 'Comparte esta imagen:',
    next: 'Siguiente',
    previous: 'Anterior',
    finished: 'He terminado',
    back: 'Regresar',
    favorite: 'Favorito',
    favoriteIcon: '<i class="fa fa-heart-o readymade-clickable-not-checked"></i>',
    favoriteIconChecked: '<i class="fa fa-heart readymade-clickable-checked" style="color: orangered;"></i>',
    hideOldMarks: 'Ocultar marcas previas',
    hideOldMarksIcon: '<i class="fa fa-eye-slash readymade-clickable-not-checked"></i>',
    hideOldMarksIconChecked: '<i class="fa fa-eye-slash readymade-clickable-checked" style="color: orangered;"></i>',
    restartTutorial: 'Ver tutorial',
    tutorialIcon: '<i class="fa fa-graduation-cap"></i>'
  };

}).call(this);
