// Generated by CoffeeScript 1.12.4
(function() {
  module.exports = {
    home: 'Home',
    classify: 'Classifica',
    profile: 'Profilo',
    science: 'Scienza',
    team: 'Team',
    getStarted: 'Inizia!',
    thankYou: 'Grazie! Your classification has been recorded.',
    yes: 'Si',
    no: 'No',
    talkQuestion: 'Do you want to talk about this image?',
    existingComments: 'There are already <span class="readymade-existing-comments-count">&mdash;</span> comments.',
    share: 'Share this image:',
    next: 'Continua',
    previous: 'Previous',
    finished: 'Fatto',
    back: 'Back',
    favorite: 'Preferito',
    favoriteIcon: '<i class="fa fa-heart-o readymade-clickable-not-checked"></i>',
    favoriteIconChecked: '<i class="fa fa-heart readymade-clickable-checked" style="color: orangered;"></i>',
    hideOldMarks: 'Hide old marks',
    hideOldMarksIcon: '<i class="fa fa-eye-slash readymade-clickable-not-checked"></i>',
    hideOldMarksIconChecked: '<i class="fa fa-eye-slash readymade-clickable-checked" style="color: orangered;"></i>',
    restartTutorial: 'Restart tutorial',
    tutorialIcon: '<i class="fa fa-graduation-cap"></i>'
  };

}).call(this);
