// Generated by CoffeeScript 1.12.4
(function() {
  module.exports = {
    home: 'ホーム',
    classify: '分類する',
    profile: 'プロフィール',
    science: 'サイエンス',
    team: 'チーム',
    getStarted: '始めよう！',
    favorite: 'お気に入り',
    favoriteIcon: '<i class="fa fa-heart-o readymade-clickable-not-checked"></i>',
    favoriteIconChecked: '<i class="fa fa-heart readymade-clickable-checked" style="color: orangered;"></i>',
    hideOldMarks: 'マークを表示しない',
    hideOldMarksIcon: '<i class="fa fa-eye-slash readymade-clickable-not-checked"></i>',
    hideOldMarksIconChecked: '<i class="fa fa-eye-slash readymade-clickable-checked" style="color: orangered;"></i>',
    restartTutorial: 'チュートリアル',
    tutorialIcon: '<i class="fa fa-graduation-cap"></i>'
  };

}).call(this);
