// Generated by CoffeeScript 1.12.4
(function() {
  module.exports = {
    home: '首頁',
    classify: '分析',
    profile: '分析記錄',
    science: '科學',
    team: '團隊',
    getStarted: '開始數企鵝！',
    thankYou: '謝謝。我們已記錄你的分析資料。',
    yes: '是',
    no: '否',
    talkQuestion: '想和其他人討論一下這張照片嗎？',
    existingComments: '已經有 <span class="readymade-existing-comments-count">&mdash;</span> 則回應',
    share: '分享這張照片：',
    next: '下一步',
    previous: '上一步',
    finished: '結束',
    back: '離開',
    favorite: '加入最愛',
    favoriteIcon: '<i class="fa fa-heart-o readymade-clickable-not-checked"></i>',
    favoriteIconChecked: '<i class="fa fa-heart readymade-clickable-checked" style="color: orangered;"></i>',
    hideOldMarks: '隱藏已完成的標記',
    hideOldMarksIcon: '<i class="fa fa-eye-slash readymade-clickable-not-checked"></i>',
    hideOldMarksIconChecked: '<i class="fa fa-eye-slash readymade-clickable-checked" style="color: orangered;"></i>',
    restartTutorial: '重看一次教學',
    tutorialIcon: '<i class="fa fa-graduation-cap"></i>'
  };

}).call(this);
