// Generated by CoffeeScript 1.9.0
(function() {
  var $, Api, ClassificationSummary, Classifier, ClassifyPage, DecisionTree, Dialog, DrawingTask, FieldGuide, MiniTutorial, StackOfPages, SubjectViewer, User, currentConfig, loginDialog, signupDialog,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __hasProp = {}.hasOwnProperty,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  Dialog = require('zooniverse/controllers/dialog');

  loginDialog = require('zooniverse/controllers/login-dialog');

  signupDialog = require('zooniverse/controllers/signup-dialog');

  Classifier = require('./classifier');

  MiniTutorial = require('./mini-tutorial');

  SubjectViewer = require('./subject-viewer');

  DecisionTree = require('zooniverse-decision-tree');

  ClassificationSummary = require('./classification-summary');

  DrawingTask = require('./tasks/drawing');

  FieldGuide = require('./field-guide');

  currentConfig = require('zooniverse-readymade/current-configuration');

  User = require('zooniverse/models/user');

  $ = window.jQuery;

  StackOfPages = require('stack-of-pages');

  Api = require('zooniverse/lib/api');

  ClassifyPage = (function(_super) {
    __extends(ClassifyPage, _super);

    ClassifyPage.prototype.START_TUTORIAL = "zooniverse-readymade:classifier:start_tutorial";

    ClassifyPage.prototype.targetSubjectID = '';

    ClassifyPage.prototype.workflow = 'untitled_workflow';

    ClassifyPage.prototype.tasks = null;

    ClassifyPage.prototype.firstTask = '';

    ClassifyPage.prototype.tutorial = null;

    ClassifyPage.prototype.tutorialSteps = null;

    ClassifyPage.prototype.examples = null;

    ClassifyPage.prototype.classificationsSubmitted = 0;

    ClassifyPage.prototype.loginPromptEvery = 5;

    ClassifyPage.prototype.className = Classifier.prototype.className + " readymade-classify-page";

    ClassifyPage.prototype.template = require('./templates/classify-page');

    ClassifyPage.prototype.elements = {
      '.readymade-no-more-subjects-message': 'noMoreSubjectsMessage',
      '.readymade-subject-viewer-container': 'subjectViewerContainer',
      '.readymade-decision-tree-container': 'decisionTreeContainer',
      '.readymade-summary-container': 'summaryContainer',
      '.readymade-field-guide-container': 'fieldGuideContainer'
    };

    function ClassifyPage() {
      ClassifyPage.__super__.constructor.apply(this, arguments);
      if (this.tutorialSteps != null) {
        this.tutorial = new MiniTutorial({
          steps: this.tutorialSteps
        });
        $(this.tutorial.el).on(this.tutorial.CLOSE_EVENT, function() {
          var _ref;
          return (_ref = User.current) != null ? _ref.setPreference('tutorial_done', true) : void 0;
        });
        this.el.append(this.tutorial.el);
      }
      this.subjectViewer = new SubjectViewer;
      this.subjectViewerContainer.append(this.subjectViewer.el);
      this.decisionTree = new DecisionTree({
        taskTypes: {
          radio: require('./tasks/radio'),
          checkbox: require('./tasks/checkbox'),
          button: require('./tasks/button'),
          filter: require('./tasks/filter'),
          drawing: DrawingTask
        },
        tasks: this.tasks,
        firstTask: this.firstTask || Object.keys(this.tasks)[0]
      });
      this.listenTo(this.decisionTree.el, this.decisionTree.LOAD_TASK, (function(_this) {
        return function(e) {
          _this.subjectViewer.setTool(null, null);
          return _this.subjectViewer.setTaskIndex(e.detail.index);
        };
      })(this));
      this.listenTo(this.decisionTree.el, DrawingTask.prototype.SELECT_TOOL, (function(_this) {
        return function(e) {
          return setTimeout(function() {
            var choice, tool, _ref;
            _ref = e.detail, tool = _ref.tool, choice = _ref.choice;
            return _this.subjectViewer.setTool(tool, choice);
          });
        };
      })(this));
      this.listenTo(this.decisionTree.el, this.decisionTree.COMPLETE, (function(_this) {
        return function() {
          return _this.finishSubject();
        };
      })(this));
      this.decisionTreeContainer.append(this.decisionTree.el);
      this.summary = new ClassificationSummary;
      this.summary.on(this.summary.DISMISS, (function(_this) {
        return function() {
          return _this.getNextSubject();
        };
      })(this));
      this.summaryContainer.append(this.summary.el);
      if (this.examples != null) {
        this.fieldGuide = new FieldGuide({
          examples: this.examples
        });
        this.fieldGuideContainer.append(this.fieldGuide.el);
      }
      this.el.on(StackOfPages.prototype.activateEvent, (function(_this) {
        return function() {
          return _this.onActivate.apply(_this, arguments);
        };
      })(this));
    }

    ClassifyPage.prototype.isUserScientist = function() {
      var project, result, talkUser;
      result = new $.Deferred;
      if (User.current != null) {
        project = Api.current.get("/projects/" + Api.current.project);
        talkUser = Api.current.get("/projects/penguin/talk/users/" + User.current.name);
        $.when(project, talkUser).then((function(_this) {
          return function(project, talkUser) {
            var details, projectRoles, _ref, _ref1, _ref2, _ref3, _ref4;
            projectRoles = (_ref = (_ref1 = talkUser.talk) != null ? (_ref2 = _ref1.roles) != null ? _ref2[project.id] : void 0 : void 0) != null ? _ref : [];
            details = {
              project: project.id,
              roles: projectRoles,
              scientist: __indexOf.call(projectRoles, 'scientist') >= 0,
              admin: __indexOf.call(projectRoles, 'admin') >= 0,
              'brian-c': (_ref3 = talkUser.name) === 'brian-c' || _ref3 === 'eatyourgreens'
            };
            if (typeof console !== "undefined" && console !== null) {
              console.log('Can you pick your own subject?', JSON.stringify(details, null, 2));
            }
            return result.resolve(__indexOf.call(projectRoles, 'scientist') >= 0 || __indexOf.call(projectRoles, 'admin') >= 0 || ((_ref4 = talkUser.name) === 'brian-c' || _ref4 === 'eatyourgreens'));
          };
        })(this));
      } else {
        result.resolve(false);
      }
      return result.promise();
    };

    ClassifyPage.prototype.onActivate = function(e) {
      var _ref;
      this.targetSubjectID = e.originalEvent.detail.subjectID;
      if (this.targetSubjectID) {
        if (this.targetSubjectID !== ((_ref = this.Subject.current) != null ? _ref.zooniverse_id : void 0)) {
          return this.getNextSubject();
        }
      }
    };

    ClassifyPage.prototype.onUserChange = function(user) {
      var tutorialDone, _ref, _ref1, _ref2;
      ClassifyPage.__super__.onUserChange.apply(this, arguments);
      this.classificationsSubmitted = 0;
      if (this.tutorial != null) {
        tutorialDone = user != null ? (_ref = user.project) != null ? _ref.tutorial_done : void 0 : void 0;
        if (tutorialDone == null) {
          tutorialDone = user != null ? (_ref1 = user.preferences) != null ? (_ref2 = _ref1[currentConfig.id]) != null ? _ref2.tutorial_done : void 0 : void 0 : void 0;
        }
        if (tutorialDone) {
          if (this.tutorial.el.hasAttribute('data-open')) {
            return this.tutorial.close();
          }
        } else {
          return this.startTutorial();
        }
      }
    };

    ClassifyPage.prototype.getNextSubject = function() {
      if (this.targetSubjectID) {
        return this.isUserScientist().then((function(_this) {
          return function(theyAre) {
            var request;
            if (theyAre) {
              request = Api.current.get("/projects/" + Api.current.project + "/subjects/" + _this.targetSubjectID);
              request.then(function(data) {
                var subject;
                subject = new _this.Subject(data);
                return subject.select();
              });
              return request.fail(function() {
                return alert("There's no subject with the ID " + _this.targetSubjectID + ".");
              });
            } else {
              alert('Sorry, only science team members can choose the subjects they classify.');
              return ClassifyPage.__super__.getNextSubject.apply(_this, arguments);
            }
          };
        })(this));
      } else {
        return ClassifyPage.__super__.getNextSubject.apply(this, arguments);
      }
    };

    ClassifyPage.prototype.startTutorial = function() {
      this.tutorial.goTo(0);
      this.tutorial.open();
      return this.trigger(this.START_TUTORIAL, this, this.tutorial);
    };

    ClassifyPage.prototype.onNoMoreSubjects = function() {
      this.noMoreSubjectsMessage.show();
      this.subjectViewerContainer.hide();
      this.decisionTreeContainer.hide();
      return this.summaryContainer.hide();
    };

    ClassifyPage.prototype.createClassification = function(subject) {
      ClassifyPage.__super__.createClassification.apply(this, arguments);
      if (subject.zooniverse_id === this.targetSubjectID) {
        return this.classification.set('chosen_subject', true);
      }
    };

    ClassifyPage.prototype.loadSubject = function(subject, callback) {
      var args;
      args = arguments;
      this.noMoreSubjectsMessage.hide();
      this.subjectViewerContainer.show();
      this.decisionTreeContainer.show();
      this.summaryContainer.hide();
      this.subjectViewer.loadSubject(subject, (function(_this) {
        return function() {
          return ClassifyPage.__super__.loadSubject.apply(_this, args);
        };
      })(this));
      return this.summary.loadSubject(subject);
    };

    ClassifyPage.prototype.loadClassification = function(classification, callback) {
      var args;
      args = arguments;
      this.decisionTree.reset();
      return this.subjectViewer.loadClassification(classification, (function(_this) {
        return function() {
          return ClassifyPage.__super__.loadClassification.apply(_this, args);
        };
      })(this));
    };

    ClassifyPage.prototype.showSummary = function() {
      this.decisionTreeContainer.hide();
      this.summaryContainer.show();
      return this.targetSubjectID = '';
    };

    ClassifyPage.prototype.sendClassification = function() {
      var annotation, _i, _len, _ref;
      this.classification.set('workflow', this.workflow);
      _ref = this.composeAnnotations();
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        annotation = _ref[_i];
        this.classification.annotate(annotation);
      }
      ClassifyPage.__super__.sendClassification.apply(this, arguments);
      this.classificationsSubmitted += 1;
      if (User.current == null) {
        if (this.classificationsSubmitted % this.loginPromptEvery === 0) {
          return this.promptToLogIn();
        }
      }
    };

    ClassifyPage.prototype.composeAnnotations = function() {
      var annotations, decisionTreeValues, key, keyAndValue, mark, task, value, _i, _j, _len, _len1, _ref;
      annotations = [];
      decisionTreeValues = this.decisionTree.getValues();
      for (_i = 0, _len = decisionTreeValues.length; _i < _len; _i++) {
        keyAndValue = decisionTreeValues[_i];
        for (key in keyAndValue) {
          value = keyAndValue[key];
          annotations.push({
            key: key,
            value: value
          });
        }
      }
      _ref = this.subjectViewer.markingSurface.tools;
      for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
        mark = _ref[_j].mark;
        task = annotations[mark._taskIndex];
        if (task != null) {
          task.value.push(mark);
        }
      }
      return annotations;
    };

    ClassifyPage.prototype.promptToLogIn = function() {
      var prompt;
      prompt = new Dialog({
        warning: true,
        content: "<header>You've submitted " + this.classificationsSubmitted + " classifications, but you're you're not logged in!</header>\n<p>Please sign in so we can make better use of your work and give you credit when the data is published.</p>\n<p class=\"action\">\n  <button name=\"close-dialog\">No thanks</button>\n  <button name=\"register\">Register</button>\n  <button name=\"sign-in\">Sign in</button>\n</p>",
        events: $.extend({}, Dialog.prototype.events, {
          'click button[name="register"]': function() {
            this.hide();
            return signupDialog.show();
          },
          'click button[name="sign-in"]': function() {
            this.hide();
            return loginDialog.show();
          }
        }),
        hide: function() {
          Dialog.prototype.hide.call(this);
          return setTimeout(((function(_this) {
            return function() {
              return _this.destroy();
            };
          })(this)), 600);
        }
      });
      return prompt.show();
    };

    ClassifyPage.prototype.events = {
      'change input[name="favorite"]': function(e) {
        return this.classification.favorite = e.target.checked;
      },
      'click button[name="restart-tutorial"]': function() {
        return this.startTutorial();
      }
    };

    return ClassifyPage;

  })(Classifier);

  module.exports = ClassifyPage;

}).call(this);
