// Generated by CoffeeScript 1.7.1
(function() {
  var Classification, Classifier, Controller, IS_DEV, Subject, User,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Controller = require('zooniverse/controllers/base-controller');

  User = require('zooniverse/models/user');

  Subject = require('zooniverse/models/subject');

  Classification = require('zooniverse/models/classification');

  IS_DEV = +location.port > 1023;

  Classifier = (function(_super) {
    __extends(Classifier, _super);

    Classifier.prototype.CREATE = "zooniverse-readymade:classifier:create";

    Classifier.prototype.START_TUTORIAL = "zooniverse-readymade:classifier:start_tutorial";

    Classifier.prototype.LOAD_SUBJECT = "zooniverse-readymade:classifier:load_subject";

    Classifier.prototype.LOAD_CLASSIFICATION = "zooniverse-readymade:classifier:load_classification";

    Classifier.prototype.CREATE_CLASSIFICATION = "zooniverse-readymade:classifier:create_classification";

    Classifier.prototype.FINISH_SUBJECT = "zooniverse-readymade:classifier:finish_subject";

    Classifier.prototype.SEND_CLASSIFICATION = "zooniverse-readymade:classifier:send_classification";

    Classifier.prototype.Subject = null;

    Classifier.prototype.subjectGroup = Subject.prototype.subjectGroup;

    Classifier.prototype.className = 'readymade-classifier';

    Classifier.prototype.tutorial = null;

    function Classifier() {
      this.Subject = (function(_super1) {
        __extends(_Class, _super1);

        function _Class() {
          return _Class.__super__.constructor.apply(this, arguments);
        }

        return _Class;

      })(Subject);
      Classifier.__super__.constructor.apply(this, arguments);
      this.Subject.group = this.subjectGroup;
      this.listenTo(User, 'change', (function(_this) {
        return function(e, user) {
          return _this.onUserChange(user);
        };
      })(this));
      this.listenTo(this.Subject, 'getting-next', (function(_this) {
        return function() {
          return _this.onSubjectGettingNext();
        };
      })(this));
      this.listenTo(this.Subject, 'select', (function(_this) {
        return function(e, subject) {
          return _this.onSubjectSelect(subject);
        };
      })(this));
      if (IS_DEV) {
        window.classifier = this;
      }
      this.trigger(this.CREATE, this);
    }

    Classifier.prototype.listenTo = function(thing, eventName, handler) {
      var addEvent, removeEvent;
      addEvent = 'on' in thing ? 'on' : 'addEventListener';
      removeEvent = 'off' in thing ? 'off' : 'removeEventListener';
      thing[addEvent](eventName, handler);
      return this.on('destroy', function() {
        return thing[removeEvent](eventName, handler);
      });
    };

    Classifier.prototype.onUserChange = function(user) {
      var tutorialDone, _ref;
      tutorialDone = user != null ? (_ref = user.project) != null ? _ref.tutorial_done : void 0 : void 0;
      if ((this.tutorial != null) && !tutorialDone) {
        return this.startTutorial();
      } else {
        if (this.classification == null) {
          return this.Subject.next();
        }
      }
    };

    Classifier.prototype.startTutorial = function() {
      this.tutorial.start();
      return this.trigger(this.START_TUTORIAL, this, this.tutorial);
    };

    Classifier.prototype.onSubjectGettingNext = function() {
      this.el.addClass('readymade-loading');
      return this.classification = null;
    };

    Classifier.prototype.onSubjectSelect = function(subject) {
      this.createClassification(subject);
      return this.loadSubject(subject, (function(_this) {
        return function(subject) {
          return _this.loadClassification(_this.classification, function(classification) {
            return _this.el.removeClass('readymade-loading');
          });
        };
      })(this));
    };

    Classifier.prototype.createClassification = function(subject) {
      this.classification = new Classification({
        subject: subject
      });
      return this.trigger(this.CREATE_CLASSIFICATION, this, this.classification);
    };

    Classifier.prototype.loadSubject = function(subject, callback) {
      if (typeof callback === "function") {
        callback(subject);
      }
      return this.trigger(this.LOAD_SUBJECT, [subject]);
    };

    Classifier.prototype.loadClassification = function(classification, callback) {
      if (typeof callback === "function") {
        callback(classification);
      }
      return this.trigger(this.LOAD_CLASSIFICATION, this, classification);
    };

    Classifier.prototype.finishSubject = function() {
      this.sendClassification();
      this.getNextSubject();
      return this.trigger(this.FINISH_SUBJECT, this, this.classification);
    };

    Classifier.prototype.sendClassification = function() {
      if (IS_DEV) {
        if (typeof console !== "undefined" && console !== null) {
          console.log(JSON.stringify(this.classification));
        }
      }
      return this.trigger(this.SEND_CLASSIFICATION, this, this.classification);
    };

    Classifier.prototype.getNextSubject = function() {
      return this.Subject.next();
    };

    return Classifier;

  })(Controller);

  module.exports = Classifier;

}).call(this);
