// Generated by CoffeeScript 1.7.1
(function() {
  var $, FieldGuide,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  $ = window.jQuery;

  FieldGuide = (function() {
    FieldGuide.prototype.examples = null;

    FieldGuide.prototype.template = function(examples) {
      var figure, i, page;
      return "<div class='readymade-field-guide-tabs'> " + (((function() {
        var _i, _len, _results;
        _results = [];
        for (i = _i = 0, _len = examples.length; _i < _len; i = ++_i) {
          page = examples[i];
          _results.push("<button name='readymade-field-guide-tab' value='" + i + "'>" + page.label + "</button>");
        }
        return _results;
      })()).join('\n')) + " </div> <div class='readymade-field-guide-pages'> " + (((function() {
        var _i, _len, _ref, _results;
        _results = [];
        for (_i = 0, _len = examples.length; _i < _len; _i++) {
          page = examples[_i];
          _results.push("<div class='readymade-field-guide-page'> <div class='readymade-field-guide-content'>" + ((_ref = page.content) != null ? _ref : '') + "</div> <div class='readymade-field-guide-examples'> " + (((function() {
            var _j, _len1, _ref1, _results1;
            _ref1 = page.figures;
            _results1 = [];
            for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
              figure = _ref1[_j];
              _results1.push("<div class='readymade-field-guide-example'> <img src='" + figure.image + "' class='readymade-field-guide-image' /> <div class='readymade-field-guide-caption'>" + figure.label + "</div> </div>");
            }
            return _results1;
          })()).join('\n')) + " </div> </div>");
        }
        return _results;
      })()).join('\n')) + " </div>";
    };

    function FieldGuide(config) {
      this.handleTabClick = __bind(this.handleTabClick, this);
      var key, renderedHTML, value;
      for (key in config) {
        value = config[key];
        this[key] = value;
      }
      if (this.examples == null) {
        this.examples = [];
      }
      if (this.el == null) {
        this.el = document.createElement('div');
      }
      this.el = $(this.el);
      this.el.addClass('readymade-field-guide');
      renderedHTML = this.template(this.examples);
      this.el.append(renderedHTML);
      this.el.on('click', '[name="readymade-field-guide-tab"]', this.handleTabClick);
      this.goTo(0);
    }

    FieldGuide.prototype.handleTabClick = function(e) {
      return this.goTo(parseFloat($(e.target).closest('[value]').val()));
    };

    FieldGuide.prototype.goTo = function(index) {
      var i, page, tab, _i, _j, _len, _len1, _ref, _ref1, _results;
      _ref = this.el.find('[name="readymade-field-guide-tab"]');
      for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
        tab = _ref[i];
        $(tab).toggleClass('active', i === index);
      }
      _ref1 = this.el.find('.readymade-field-guide-page');
      _results = [];
      for (i = _j = 0, _len1 = _ref1.length; _j < _len1; i = ++_j) {
        page = _ref1[i];
        _results.push($(page).toggle(i === index));
      }
      return _results;
    };

    FieldGuide.prototype.destroy = function() {
      return this.el.off('click', '[readymade-field-guide-tab]', this.handleTabClick);
    };

    return FieldGuide;

  })();

  module.exports = FieldGuide;

}).call(this);
