// Generated by CoffeeScript 1.7.1
(function() {
  var $, FieldGuide, TabSet,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  $ = window.jQuery;

  TabSet = require('./tab-control');

  FieldGuide = (function() {
    FieldGuide.prototype.examples = null;

    FieldGuide.prototype.template = function(examples) {
      var figure, i, page;
      return "<div class='readymade-field-guide-tabs'> " + (((function() {
        var _i, _len, _results;
        _results = [];
        for (i = _i = 0, _len = examples.length; _i < _len; i = ++_i) {
          page = examples[i];
          _results.push("<button id='fg-tab-" + i + "' name='readymade-field-guide-tab'>" + page.label + "</button>");
        }
        return _results;
      })()).join('\n')) + " </div> <div class='readymade-field-guide-pages'> " + (((function() {
        var _i, _len, _ref, _results;
        _results = [];
        for (i = _i = 0, _len = examples.length; _i < _len; i = ++_i) {
          page = examples[i];
          _results.push("<div class='readymade-field-guide-page'> <div class='readymade-field-guide-content'>" + ((_ref = page.content) != null ? _ref : '') + "</div> <div class='readymade-field-guide-examples'> " + (((function() {
            var _j, _len1, _ref1, _results1;
            _ref1 = page.figures;
            _results1 = [];
            for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
              figure = _ref1[_j];
              _results1.push("<div class='readymade-field-guide-example'> <img src='" + figure.image + "' alt='" + figure.alt + "' class='readymade-field-guide-image' /> <div class='readymade-field-guide-caption'>" + figure.label + "</div> </div>");
            }
            return _results1;
          })()).join('\n')) + " </div> </div>");
        }
        return _results;
      })()).join('\n')) + " </div>";
    };

    function FieldGuide(config) {
      this.goTo = __bind(this.goTo, this);
      this.handleTabClick = __bind(this.handleTabClick, this);
      var key, renderedHTML, value;
      for (key in config) {
        value = config[key];
        this[key] = value;
      }
      if (this.examples == null) {
        this.examples = [];
      }
      if (this.el == null) {
        this.el = document.createElement('div');
      }
      this.el = $(this.el);
      this.el.addClass('readymade-field-guide');
      renderedHTML = this.template(this.examples);
      this.el.append(renderedHTML);
      this.tabs = new TabSet;
      this.el.find('.readymade-field-guide-page').each((function(_this) {
        return function(i, panel) {
          var tab;
          tab = _this.el.find("#fg-tab-" + i);
          return _this.tabs.add(tab, panel, i === 0);
        };
      })(this));
      this.el.on('focus', 'button[role=tab]', this.handleTabClick);
      this.goTo(0);
    }

    FieldGuide.prototype.handleTabClick = function(e) {
      var index;
      index = e.target.id.replace('fg-tab-', '');
      return this.goTo(index);
    };

    FieldGuide.prototype.goTo = function(index) {
      return this.tabs.goTo(parseInt(index));
    };

    FieldGuide.prototype.destroy = function() {
      this.el.off('focus', 'button[role=tab]', this.handleTabClick);
      return this.tabs.destroy();
    };

    return FieldGuide;

  })();

  module.exports = FieldGuide;

}).call(this);
