// Generated by CoffeeScript 1.9.1
(function() {
  var $, FieldGuide,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  $ = window.jQuery;

  FieldGuide = (function() {
    FieldGuide.prototype.examples = null;

    FieldGuide.prototype.template = function(examples) {
      var figure, i, page;
      return "<div class='readymade-field-guide-tabs'> " + (((function() {
        var j, len, results;
        results = [];
        for (i = j = 0, len = examples.length; j < len; i = ++j) {
          page = examples[i];
          results.push("<button name='readymade-field-guide-tab' value='" + i + "'>" + page.label + "</button>");
        }
        return results;
      })()).join('\n')) + " </div> <div class='readymade-field-guide-pages'> " + (((function() {
        var j, len, ref, results;
        results = [];
        for (j = 0, len = examples.length; j < len; j++) {
          page = examples[j];
          results.push("<div class='readymade-field-guide-page'> <div class='readymade-field-guide-content'>" + ((ref = page.content) != null ? ref : '') + "</div> <div class='readymade-field-guide-examples'> " + (((function() {
            var k, len1, ref1, results1;
            ref1 = page.figures;
            results1 = [];
            for (k = 0, len1 = ref1.length; k < len1; k++) {
              figure = ref1[k];
              results1.push("<div class='readymade-field-guide-example'> <img src='" + figure.image + "' class='readymade-field-guide-image' /> <div class='readymade-field-guide-caption'>" + figure.label + "</div> </div>");
            }
            return results1;
          })()).join('\n')) + " </div> </div>");
        }
        return results;
      })()).join('\n')) + " </div>";
    };

    function FieldGuide(config) {
      this.handleTabClick = bind(this.handleTabClick, this);
      var key, renderedHTML, value;
      for (key in config) {
        value = config[key];
        this[key] = value;
      }
      if (this.examples == null) {
        this.examples = [];
      }
      if (this.el == null) {
        this.el = document.createElement('div');
      }
      this.el = $(this.el);
      this.el.addClass('readymade-field-guide');
      renderedHTML = this.template(this.examples);
      this.el.append(renderedHTML);
      this.el.on('click', '[name="readymade-field-guide-tab"]', this.handleTabClick);
      this.goTo(0);
    }

    FieldGuide.prototype.handleTabClick = function(e) {
      return this.goTo(parseFloat($(e.target).closest('[value]').val()));
    };

    FieldGuide.prototype.goTo = function(index) {
      var i, j, k, len, len1, page, ref, ref1, results, tab;
      ref = this.el.find('[name="readymade-field-guide-tab"]');
      for (i = j = 0, len = ref.length; j < len; i = ++j) {
        tab = ref[i];
        $(tab).toggleClass('active', i === index);
      }
      ref1 = this.el.find('.readymade-field-guide-page');
      results = [];
      for (i = k = 0, len1 = ref1.length; k < len1; i = ++k) {
        page = ref1[i];
        results.push($(page).toggle(i === index));
      }
      return results;
    };

    FieldGuide.prototype.destroy = function() {
      return this.el.off('click', '[readymade-field-guide-tab]', this.handleTabClick);
    };

    return FieldGuide;

  })();

  module.exports = FieldGuide;

}).call(this);
