// Generated by CoffeeScript 1.12.4
(function() {
  var Api, ClassifyPage, Profile, Project, SiteBackground, SiteHeader, StackOfPages, TabSet, TopBar, User, ZooniverseFooter, dash, homePageTemplate, ref, ref1, ref2, ref3, ref4, ref5, ref6, ref7, ref8, ref9, teamPageTemplate, translate,
    slice = [].slice;

  Api = ((ref = window.zooniverse) != null ? ref.Api : void 0) || require('zooniverse/lib/api');

  TopBar = ((ref1 = window.zooniverse) != null ? (ref2 = ref1.controllers) != null ? ref2.TopBar : void 0 : void 0) || require('zooniverse/controllers/top-bar');

  SiteBackground = require('./site-background');

  SiteHeader = require('./site-header');

  StackOfPages = require('stack-of-pages');

  translate = ((ref3 = window.zooniverse) != null ? ref3.translate : void 0) || require('zooniverse/lib/translate');

  homePageTemplate = require('./templates/home-page');

  ZooniverseFooter = ((ref4 = window.zooniverse) != null ? (ref5 = ref4.controllers) != null ? ref5.Footer : void 0 : void 0) || require('zooniverse/controllers/footer');

  dash = require('./lib/dash');

  ClassifyPage = require('./classify-page');

  Profile = ((ref6 = window.zooniverse) != null ? (ref7 = ref6.controllers) != null ? ref7.Profile : void 0 : void 0) || require('zooniverse/controllers/profile');

  teamPageTemplate = require('./templates/team-page');

  User = ((ref8 = window.zooniverse) != null ? (ref9 = ref8.models) != null ? ref9.User : void 0 : void 0) || require('zooniverse/models/user');

  TabSet = require('./tab-control');

  Project = (function() {
    Project.prototype.parent = document.body;

    Project.prototype.background = '';

    Project.prototype.id = '';

    Project.prototype.apiHost = null;

    Project.prototype.apiProxyPath = null;

    Project.prototype.producer = '';

    Project.prototype.title = '';

    Project.prototype.summary = '';

    Project.prototype.description = '';

    Project.prototype.about = '';

    Project.prototype.pages = null;

    Project.prototype.workflows = null;

    Project.prototype.tasks = null;

    Project.prototype.firstTask = '';

    Project.prototype.subjectGroup = false;

    Project.prototype.organizations = null;

    Project.prototype.scientists = null;

    Project.prototype.developers = null;

    function Project(configuration) {
      var examples, firstTask, footer, hash, href, j, k, key, label, len, len1, newContent, page, property, ref10, ref11, ref12, ref13, subjectGroup, tasks, title, tmp, tutorialSteps, value;
      if (configuration == null) {
        configuration = {};
      }
      for (property in configuration) {
        value = configuration[property];
        this[property] = value;
      }
      if (this.background) {
        this.siteBackground = new SiteBackground({
          src: this.background,
          el: '#site-background'
        });
      }
      if (this.id) {
        this.connect();
      }
      this.header = new SiteHeader({
        el: '#main-header',
        template: SiteHeader.prototype.template(this)
      });
      this.stack = new StackOfPages({
        el: document.getElementById('main-content'),
        changeDisplay: false
      });
      this.stack.el.className += ' readymade-main-stack';
      if (this.summary || this.description) {
        this.homePage = this.addPage('#/', translate('readymade.home'), homePageTemplate(this));
        if (this.footer !== false) {
          footer = new ZooniverseFooter;
          footer.el.appendTo('#main-footer');
        }
      }
      this.classifyPages = [];
      if (this.workflows != null) {
        ref10 = this.workflows;
        for (j = 0, len = ref10.length; j < len; j++) {
          ref11 = ref10[j], key = ref11.key, label = ref11.label, subjectGroup = ref11.subjectGroup, tasks = ref11.tasks, firstTask = ref11.firstTask, tutorialSteps = ref11.tutorialSteps, examples = ref11.examples;
          if (label == null) {
            label = translate('readymade.classify');
          }
          if (key == null) {
            key = dash(label).replace(/\-/g, '_');
          }
          page = new ClassifyPage({
            subjectGroup: subjectGroup != null ? subjectGroup : this.subjectGroup,
            workflow: key,
            tasks: tasks,
            firstTask: firstTask,
            tutorialSteps: tutorialSteps,
            examples: examples
          });
          this.addPage("#/" + (dash(label)) + "/:subjectID", label, page);
          this.classifyPages.push(page);
        }
      } else if (this.tasks != null) {
        page = new ClassifyPage({
          tasks: this.tasks,
          firstTask: this.firstTask,
          subjectGroup: this.subjectGroup,
          tutorialSteps: this.tutorialSteps,
          examples: this.examples
        });
        this.addPage('#/classify/:subjectID', translate('readymade.classify'), page);
        this.classifyPages.push(page);
      }
      if (this.profile !== false) {
        this.profile = new Profile;
        this.addPage('#/profile', translate('readymade.profile'), this.profile);
      }
      if (this.pages != null) {
        tmp = document.createElement('div');
        ref12 = this.pages;
        for (k = 0, len1 = ref12.length; k < len1; k++) {
          page = ref12[k];
          if (page.content instanceof Array) {
            newContent = this.makeStackFromPages(page.content, [page.key]);
          } else if (typeof page.content === 'string') {
            newContent = "<div class='readymade-generic-page' data-readymade-page='" + page.key + "'>" + page.content + "</div>";
          } else {
            newContent = page.content;
          }
          hash = "#/" + page.key;
          this.addPage(hash, page.title, newContent);
        }
      }
      if (this.organizations || this.scientists || this.developers) {
        this.addPage('#/team', translate('readymade.team'), teamPageTemplate(this));
      }
      this.buildNavTabs(this.header.linksList, 'nav');
      if (this.externalLinks != null) {
        ref13 = this.externalLinks;
        for (title in ref13) {
          href = ref13[title];
          this.header.addNavLink(href, title);
        }
      }
      setTimeout((function(_this) {
        return function() {
          return _this.stack.onHashChange();
        };
      })(this));
      User.fetch();
    }

    Project.prototype.makeStackFromPages = function(pages, currentPath) {
      var container, hash, i, id, j, len, mapOfHashes, nav, page, prefix, stack;
      if (currentPath == null) {
        currentPath = [];
      }
      mapOfHashes = {
        changeDisplay: false
      };
      prefix = currentPath[currentPath.length - 1];
      nav = document.createElement('nav');
      nav.className = 'readymade-subnav';
      for (i = j = 0, len = pages.length; j < len; i = ++j) {
        page = pages[i];
        id = page.key;
        currentPath.push(id);
        hash = ['#'].concat(slice.call(currentPath)).join('/');
        if (mapOfHashes["default"] == null) {
          mapOfHashes["default"] = hash;
        }
        nav.appendChild(this.navLink(id, hash, page.title));
        mapOfHashes[hash] = page.content instanceof Array ? this.makeStackFromPages(page.content, currentPath) : typeof page.content === 'string' ? "<div id='" + id + "' class='readymade-generic-page' data-readymade-page='" + page.key + "'>" + page.content + "</div>" : (container = document.createElement('div'), page.content);
        currentPath.pop();
      }
      stack = new StackOfPages(mapOfHashes);
      stack.el.insertBefore(nav, stack.el.firstChild);
      setTimeout(function() {
        return stack.onHashChange();
      });
      this.buildNavTabs(nav, prefix, stack);
      return stack;
    };

    Project.prototype.connect = function() {
      this.api = new Api({
        project: this.id,
        host: this.apiHost,
        path: this.apiProxyPath
      });
      return this.topBar = new TopBar({
        el: '#top-bar'
      });
    };

    Project.prototype.addPage = function(href, label, content) {
      var frag_id, link, linkHREF, page;
      linkHREF = href.replace(/\/:[^\/]+/g, '');
      frag_id = linkHREF.split('/').pop();
      if (frag_id === '') {
        frag_id = 'home';
      }
      if (content instanceof StackOfPages) {
        href += "/*";
      }
      this.stack.add(href, content);
      page = this.stack.el.children[this.stack.el.children.length - 1];
      page.id = frag_id;
      link = this.header.addNavLink('#' + frag_id, label);
      link.addEventListener('click', function(e) {
        window.location.hash = linkHREF;
        return e.preventDefault();
      });
      return page;
    };

    Project.prototype.navLink = function(id, hash, title) {
      var link;
      link = document.createElement('a');
      link.href = '#' + id;
      link.innerHTML = title;
      link.addEventListener('click', (function(_this) {
        return function(e) {
          e.preventDefault();
          return window.location.hash = hash;
        };
      })(this));
      return link;
    };

    Project.prototype.buildNavTabs = function(nav, prefix, stack) {
      var hash, j, len, link, nav_links, panel, panels, ref10;
      if (stack == null) {
        stack = this.stack;
      }
      nav_links = [];
      panels = [];
      if (nav[0] != null) {
        nav = nav[0];
      }
      ref10 = nav.querySelectorAll('a');
      for (j = 0, len = ref10.length; j < len; j++) {
        link = ref10[j];
        hash = link.getAttribute('href');
        panel = stack.el.querySelector(hash);
        if (panel != null) {
          panels.push(panel);
          nav_links.push(link);
        }
      }
      return this.buildTabset(nav_links, panels, prefix, stack);
    };

    Project.prototype.buildTabset = function(tabs, panels, prefix, stack) {
      var i, j, len, panel, results, tab, tabset;
      tabset = new TabSet;
      results = [];
      for (i = j = 0, len = tabs.length; j < len; i = ++j) {
        tab = tabs[i];
        panel = panels[i];
        if (tab.id === '') {
          tab.id = prefix + '-tab-' + i;
        }
        if (panel.id === '') {
          panel.id = prefix + '-' + i;
        }
        tabset.add(tab, panel, panel.hasAttribute(stack.activatedAttr));
        results.push((function(panel) {
          return panel.addEventListener(stack.activateEvent, function(e) {
            e.stopPropagation();
            return tabset.activate(panel);
          });
        })(panel));
      }
      return results;
    };

    return Project;

  })();

  module.exports = Project;

}).call(this);
