// Generated by CoffeeScript 1.7.1
(function() {
  var Controller, SiteHeader,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Controller = require('zooniverse/controllers/base-controller');

  SiteHeader = (function(_super) {
    __extends(SiteHeader, _super);

    function SiteHeader() {
      return SiteHeader.__super__.constructor.apply(this, arguments);
    }

    SiteHeader.prototype.className = 'readymade-site-header';

    SiteHeader.prototype.template = require('./templates/site-header');

    SiteHeader.prototype.elements = {
      '.readymade-site-links': 'linksList'
    };

    SiteHeader.prototype.addNavLink = function(href, label) {
      return this.linksList.append("<a href='" + href + "' class='readymade-site-link'>" + label + "</a>\n");
    };

    return SiteHeader;

  })(Controller);

  module.exports = SiteHeader;

}).call(this);
