// Generated by CoffeeScript 1.8.0
(function() {
  var BasePoint, Point, SVG,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BasePoint = require('marking-surface/lib/tools/point');

  SVG = require('marking-surface').SVG;

  Point = (function(_super) {
    __extends(Point, _super);

    Point.Controls = require('./tool-controls');

    Point.prototype.unit = '';

    Point.prototype.upp = 0;

    Point.prototype.precision = 0;

    function Point() {
      Point.__super__.constructor.apply(this, arguments);
      this.label.el.style.display = 'none';
    }

    return Point;

  })(BasePoint);

  module.exports = Point;

}).call(this);
