// Generated by CoffeeScript 1.9.0
(function() {
  var flag, flags, _i, _len, _ref;

  flags = ['dev'];

  module.exports = {};

  for (_i = 0, _len = flags.length; _i < _len; _i++) {
    flag = flags[_i];
    module.exports[flag] = parseFloat((_ref = location.search.match(flag + "=(\\d+)")) != null ? _ref[1] : void 0) || null;
  }

}).call(this);
