// Generated by CoffeeScript 1.12.4
(function() {
  var flag, flags, i, len, ref;

  flags = ['dev'];

  module.exports = {};

  for (i = 0, len = flags.length; i < len; i++) {
    flag = flags[i];
    module.exports[flag] = parseFloat((ref = location.search.match(flag + "=(\\d+)")) != null ? ref[1] : void 0) || null;
  }

}).call(this);
