// Generated by CoffeeScript 1.9.3
(function() {
  var typeMap;

  typeMap = {
    'drawing': 'radio',
    'filter': 'radio'
  };

  module.exports = function(choice, i) {
    var ref, ref1, ref2, ref3, ref4, ref5, ref6, ref7;
    return "<label class='readymade-choice-input-wrapper'> <input type='" + ((ref = (ref1 = (ref2 = typeMap[(ref3 = this.constructor) != null ? ref3.type : void 0]) != null ? ref2 : typeMap[this.type]) != null ? ref1 : (ref4 = this.constructor) != null ? ref4.type : void 0) != null ? ref : this.type) + "' name='" + this.key + "' value='" + choice.value + "' " + (choice.checked ? 'checked="checked"' : '') + " data-choice-index='" + i + "' /> <div class='readymade-choice-clickable readymade-choice-" + ((ref5 = this.constructor.type) != null ? ref5 : this.type) + "'> <div class='readymade-choice-tickbox'> <div class='readymade-choice-tick'></div> </div> " + (choice.image != null ? "<div class='readymade-choice-image'><img src='" + choice.image + "' /></div>" : '') + " <div class='readymade-choice-label'>" + ((ref6 = (ref7 = choice.label) != null ? ref7 : choice.value) != null ? ref6 : i) + "</div> " + (choice.color != null ? "<div class='readymade-choice-color' style='color: " + choice.color + ";'></div>" : '') + " </div> </label>";
  };

}).call(this);
