// Generated by CoffeeScript 1.7.1
(function() {
  var typeMap;

  typeMap = {
    'drawing': 'radio',
    'filter': 'radio'
  };

  module.exports = function(choice, i) {
    var _ref, _ref1, _ref2, _ref3, _ref4, _ref5, _ref6, _ref7;
    return "<label class='readymade-choice-input-wrapper'> <input type='" + ((_ref = (_ref1 = (_ref2 = typeMap[(_ref3 = this.constructor) != null ? _ref3.type : void 0]) != null ? _ref2 : typeMap[this.type]) != null ? _ref1 : (_ref4 = this.constructor) != null ? _ref4.type : void 0) != null ? _ref : this.type) + "' name='" + this.key + "' value='" + choice.value + "' data-choice-index='" + i + "' /> <div class='readymade-choice-clickable readymade-choice-" + ((_ref5 = this.constructor.type) != null ? _ref5 : this.type) + "'> <div class='readymade-choice-tickbox'> <div class='readymade-choice-tick'></div> </div> " + (choice.image != null ? "<div class='readymade-choice-image'><img src='" + choice.image + "' /></div>" : '') + " <div class='readymade-choice-label'>" + ((_ref6 = (_ref7 = choice.label) != null ? _ref7 : choice.value) != null ? _ref6 : i) + "</div> " + (choice.color != null ? "<div class='readymade-choice-color' style='color: " + choice.color + ";'></div>" : '') + " </div> </label>";
  };

}).call(this);
