// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function() {
    return '<div class="readymade-classification-interface"> <div class="readymade-subject-viewer-container"></div> <div class="readymade-decision-tree-container"></div> </div>';
  };

}).call(this);
