// Generated by CoffeeScript 1.9.1
(function() {
  module.exports = function() {
    return '<div class="readymade-classification-interface"> <div class="readymade-no-more-subjects-message" style="display: none;"> <p>Looks like we\'re temporarily out of data to classify. Please check back later!</p> <p>In the meantime, <a href="https://www.zooniverse.org/">check out some other projects in the Zooniverse!</a></p> </div> <div class="readymade-subject-viewer-container"></div> <div class="readymade-decision-tree-container" style="display: none;"></div> <div class="readymade-summary-container" style="display: none;"></div> </div> <div class="readymade-field-guide-container"></div>';
  };

}).call(this);
