// Generated by CoffeeScript 1.12.4
(function() {
  var ref, translate;

  translate = ((ref = window.zooniverse) != null ? ref.translate : void 0) || require('zooniverse/lib/translate');

  module.exports = function() {
    return (translate('p', 'readymade.thankYou')) + " <div> <p> " + (translate('readymade.talkQuestion')) + " <span class='readymade-existing-comments'> " + (translate('readymade.existingComments')) + " </span> </p> <p class='readymade-talk'> <button type='button' name='readymade-dont-talk'>" + (translate('readymade.no')) + "</button> <a href='#' class='readymade-talk-link'>" + (translate('readymade.yes')) + "</a> </p> </div> " + (location.href.indexOf('beta') === -1 ? "<div> <p> " + (translate('readymade.share')) + " </p> <p class='readymade-social'> <a href='#' class='readymade-facebook-link'><i class='fa fa-facebook-square'></i></a> <a href='#' class='readymade-twitter-link'><i class='fa fa-twitter'></i></a> </p> </div>" : '');
  };

}).call(this);
