// Generated by CoffeeScript 1.9.3
(function() {
  var dash, translate;

  translate = require('zooniverse/lib/translate');

  dash = require('../lib/dash');

  module.exports = function(context) {
    var template;
    template = function() {
      var label, name, ref, workflows;
      workflows = (ref = this.workflows) != null ? ref : [
        {
          label: translate('readymade.getStarted'),
          name: 'classify'
        }
      ];
      return "<div class='readymade-home-page'> <div class='readymade-home-page-content'> " + (this.summary ? "<div class='readymade-project-summary'> " + this.summary + " </div>" : '') + " " + (this.description ? "<div class='readymade-project-description'> " + this.description + " </div>" : '') + " <div class='readymade-footer'> " + (((function() {
        var i, len, ref1, results;
        results = [];
        for (i = 0, len = workflows.length; i < len; i++) {
          ref1 = workflows[i], name = ref1.name, label = ref1.label;
          results.push("<a href='#/" + (name != null ? name : dash(label)) + "' class='readymade-call-to-action'> " + label + " </a>");
        }
        return results;
      })()).join('\n')) + " </div> </div> </div>";
    };
    return template.call(context);
  };

}).call(this);
