// Generated by CoffeeScript 1.9.0
(function() {
  var dash;

  dash = require('../lib/dash');

  module.exports = function(context) {
    var template;
    template = function() {
      var label, name, workflows, _ref;
      workflows = (_ref = this.workflows) != null ? _ref : [
        {
          label: 'Get started!',
          name: 'classify'
        }
      ];
      return "<div class='readymade-home-page'> <div class='readymade-home-page-content'> " + (this.summary ? "<div class='readymade-project-summary'> " + this.summary + " </div>" : '') + " " + (this.description ? "<div class='readymade-project-description'> " + this.description + " </div>" : '') + " <div class='readymade-footer'> " + (((function() {
        var _i, _len, _ref1, _results;
        _results = [];
        for (_i = 0, _len = workflows.length; _i < _len; _i++) {
          _ref1 = workflows[_i], name = _ref1.name, label = _ref1.label;
          _results.push("<a href='#/" + (name != null ? name : dash(label)) + "' class='readymade-call-to-action'> " + label + " </a>");
        }
        return _results;
      })()).join('\n')) + " </div> </div> </div>";
    };
    return template.call(context);
  };

}).call(this);
