// Generated by CoffeeScript 1.12.3
(function() {
  var dash, ref, translate;

  translate = ((ref = window.zooniverse) != null ? ref.translate : void 0) || require('zooniverse/lib/translate');

  dash = require('../lib/dash');

  module.exports = function(context) {
    var template;
    template = function() {
      var label, name, ref1, workflows;
      workflows = (ref1 = this.workflows) != null ? ref1 : [
        {
          label: translate('readymade.getStarted'),
          name: 'classify'
        }
      ];
      return "<div class='readymade-home-page'> <div class='readymade-home-page-content'> " + (this.summary ? "<div class='readymade-project-summary'> " + this.summary + " </div>" : '') + " " + (this.description ? "<div class='readymade-project-description'> " + this.description + " </div>" : '') + " <div class='readymade-footer'> " + (((function() {
        var i, len, ref2, results;
        results = [];
        for (i = 0, len = workflows.length; i < len; i++) {
          ref2 = workflows[i], name = ref2.name, label = ref2.label;
          results.push("<a href='#/" + (name != null ? name : dash(label)) + "' class='readymade-call-to-action'> " + label + " </a>");
        }
        return results;
      })()).join('\n')) + " </div> </div> </div>";
    };
    return template.call(context);
  };

}).call(this);
