// Generated by CoffeeScript 1.9.0
(function() {
  module.exports = function(context) {
    var template;
    template = function() {
      return "<div class='readymade-creator'> <a href='#/'> <div class='readymade-project-producer'>" + this.producer + "</div> <div class='readymade-project-title'>" + this.title + "</div> </a> </div> <div class='readymade-site-links'></div>";
    };
    return template.call(context);
  };

}).call(this);
