// Generated by CoffeeScript 1.9.1
(function() {
  module.exports = function(context) {
    var template;
    template = function() {
      return "<div class='readymade-creator'> <a href='#/'> <div class='readymade-project-producer'>" + this.producer + "</div> <h1 class='readymade-project-title'>" + this.title + "</h1> </a> </div> <ul class='readymade-site-links' role='navigation'></ul>";
    };
    return template.call(context);
  };

}).call(this);
