// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function() {
    return '<div class="drawing-controls"> <label><input type="checkbox" name="hide-old-marks" />Hide old marks</label> </div> <div class="readymade-marking-surface-container"></div> <div class="readymade-frame-controls"> <div class="readymade-frame-play-controls"> <button name="play-frames">►</button> <button name="pause-frames">◼</button> </div> <div class="readymade-frame-toggles-list"></div> </div>';
  };

}).call(this);
