// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(context) {
    var template;
    template = function() {
      var group, grouping, i, member, url;
      return "<div class='readymade-team-page'> " + (((function() {
        var j, len, ref, results;
        ref = ['organizations', 'scientists', 'developers'];
        results = [];
        for (j = 0, len = ref.length; j < len; j++) {
          group = ref[j];
          if (this[group] != null) {
            results.push("<h2 class='readymade-team-group-title'> " + (group === 'organizations' ? "Organizations" : group === 'scientists' ? "Scientists" : group === 'developers' ? "Developers" : '') + " </h2> <div class='readymade-" + group + " readymade-team-group'> " + (((function() {
              var k, len1, ref1, results1;
              ref1 = this[group];
              results1 = [];
              for (i = k = 0, len1 = ref1.length; k < len1; i = ++k) {
                member = ref1[i];
                results1.push("<div class='readymade-team-member'> " + (member.image != null ? "<div class='readymade-team-member-photo'><img src='" + member.image + "' /></div>" : '') + " <div class='readymade-team-member-header'> " + (member.name != null ? "<span class='readymade-team-member-name'>" + member.name + "</span>" : '') + " " + (member.url != null ? "<span class='readymade-member-links'> " + (((function() {
                  var l, len2, ref2, results2;
                  ref2 = [].concat(member.url);
                  results2 = [];
                  for (l = 0, len2 = ref2.length; l < len2; l++) {
                    url = ref2[l];
                    results2.push("<a href='" + url + "' class='readymade-member-url'> " + (url.match('facebook.com/') ? "<i class='fa fa-lg fa-facebook-square'></i>" : url.match('github.com/') ? "<i class='fa fa-lg fa-github-alt'></i>" : url.match('plus.google.com/') ? "<i class='fa fa-lg fa-google-plus'></i>" : url.match('linkedin.com/') ? "<i class='fa fa-lg fa-linkedin-square'></i>" : url.match('twitter.com/') ? "<i class='fa fa-lg fa-twitter'></i>" : url.match('mailto:') ? "<i class='fa fa-lg fa-envelope'></i>" : "<i class='fa fa-lg fa-globe'></i>") + " </a>");
                  }
                  return results2;
                })()).join('\n')) + " </span>" : '') + " " + (member.title != null ? "<div class='readymade-team-member-title'>" + member.title + "</div>" : '') + " " + (member.location != null ? "<div class='readymade-team-member-location'>" + member.location + "</div>" : '') + " </div> <div class='readymade-team-member-description'> " + (member.description != null ? "" + member.description : '') + " </div> </div> <!--" + (((function() {
                  var l, results2;
                  results2 = [];
                  for (grouping = l = 2; l < 5; grouping = ++l) {
                    if ((i + 1) % grouping === 0) {
                      results2.push("<span class='readymade-set-of-" + grouping + "'></span>");
                    }
                  }
                  return results2;
                })()).join('\n')) + "-->");
              }
              return results1;
            }).call(this)).join('\n')) + " </div>");
          }
        }
        return results;
      }).call(this)).join('\n')) + " </div>";
    };
    return template.call(context);
  };

}).call(this);
