// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = function(context) {
    var template;
    template = function() {
      var group, grouping, i, member, url;
      return "<div class='readymade-team-page'> " + (((function() {
        var _i, _len, _ref, _results;
        _ref = ['organizations', 'scientists', 'developers'];
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          group = _ref[_i];
          if (this[group] != null) {
            _results.push("<div class='readymade-team-group-title'> " + (group === 'organizations' ? "Organizations" : group === 'scientists' ? "Scientists" : group === 'developers' ? "Developers" : '') + " </div> <div class='readymade-" + group + " readymade-team-group'> " + (((function() {
              var _j, _len1, _ref1, _results1;
              _ref1 = this[group];
              _results1 = [];
              for (i = _j = 0, _len1 = _ref1.length; _j < _len1; i = ++_j) {
                member = _ref1[i];
                _results1.push("<div class='readymade-team-member'> " + (member.image != null ? "<div class='readymade-team-member-photo'><img src='" + member.image + "' /></div>" : '') + " <div class='readymade-team-member-header'> " + (member.name != null ? "<span class='readymade-team-member-name'>" + member.name + "</span>" : '') + " " + (member.url != null ? "<span class='readymade-member-links'> " + (((function() {
                  var _k, _len2, _ref2, _results2;
                  _ref2 = [].concat(member.url);
                  _results2 = [];
                  for (_k = 0, _len2 = _ref2.length; _k < _len2; _k++) {
                    url = _ref2[_k];
                    _results2.push("<a href='" + url + "' class='readymade-member-url'> " + (url.match('facebook.com/') ? "<i class='fa fa-lg fa-facebook-square'></i>" : url.match('github.com/') ? "<i class='fa fa-lg fa-github-alt'></i>" : url.match('plus.google.com/') ? "<i class='fa fa-lg fa-google-plus'></i>" : url.match('linkedin.com/') ? "<i class='fa fa-lg fa-linkedin-square'></i>" : url.match('twitter.com/') ? "<i class='fa fa-lg fa-twitter'></i>" : url.match('mailto:') ? "<i class='fa fa-lg fa-envelope'></i>" : "<i class='fa fa-lg fa-globe'></i>") + " </a>");
                  }
                  return _results2;
                })()).join('\n')) + " </span>" : '') + " " + (member.title != null ? "<div class='readymade-team-member-title'>" + member.title + "</div>" : '') + " " + (member.location != null ? "<div class='readymade-team-member-location'>" + member.location + "</div>" : '') + " </div> <div class='readymade-team-member-description'> " + (member.description != null ? "" + member.description : '') + " </div> </div> <!--" + (((function() {
                  var _k, _results2;
                  _results2 = [];
                  for (grouping = _k = 2; _k < 5; grouping = ++_k) {
                    if ((i + 1) % grouping === 0) {
                      _results2.push("<span class='readymade-set-of-" + grouping + "'></span>");
                    }
                  }
                  return _results2;
                })()).join('\n')) + "-->");
              }
              return _results1;
            }).call(this)).join('\n')) + " </div>");
          }
        }
        return _results;
      }).call(this)).join('\n')) + " </div>";
    };
    return template.call(context);
  };

}).call(this);
